# Generated by Django 3.2.8 on 2025-11-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20251114_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'is_active')},
        ),
    ]
